annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/display-name: External IP Webhook
  catalog.cattle.io/namespace: cattle-externalip-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: rancher-externalip-webhook
  catalog.cattle.io/ui-component: rancher-externalip-webhook
apiVersion: v1
appVersion: v0.1.6
description: |
  Deploy the externalip-webhook to mitigate k8s CVE-2020-8554
home: https://github.com/rancher/externalip-webhook
keywords:
- cve
- externalip
- webhook
- security
maintainers:
- email: raul@rancher.com
  name: rawmind0
name: rancher-externalip-webhook
sources:
- https://github.com/rancher/externalip-webhook
version: 0.1.6
