apiVersion: v1
appVersion: v2.0.0
description: K8s-TrilioVault-Operator is an operator designed to manage the K8s-TrilioVault Application Lifecycle.
home: https://github.com/trilioData/k8s-triliovault
icon: file://chart-icon.png
maintainers:
- email: prafull.ladha@trilio.io
  name: ladhaprafull
name: k8s-triliovault-operator
sources:
- https://github.com/trilioData/k8s-triliovault
version: v2.0.0
